### ISSUE TITLE
[Add Documentation] Needs more Instructions: Nothing's working

### ISSUE THREAD

**Issue by Jack-O-Brian** [Ciaxur/CPU-FrequencyManager#1]
![image](https://user-images.githubusercontent.com/40522299/81128320-dee3b300-8f0e-11ea-97e2-c9b7b26fb877.png)
I get this. How to make it do stuff?

**Comment by Ciaxur** [comment]
The program does not output anything to stdout. Send a screenshot of your resources over time, to see if your CPU's frequency is changing.

**Comment by Ciaxur** [comment]
I added some Documentation in [README](https://github.com/Ciaxur/CPU-FrequencyManager/blob/2bdb37e/README.md). Can you run the program in debug mode: `sudo go run ./src -d`?

**Comment by Jack-O-Brian** [comment]
I see some data now.
![image](https://user-images.githubusercontent.com/40522299/82597108-75061300-9b76-11ea-8476-eaa1110ec3a5.png)
